spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yhline
    password: 123yunhua
    url: jdbc:mysql://localhost:3306/library

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/**/*.xml
server:
  port: 8081